######################################################################
# Automatically generated by qmake (3.0) Tue Jul 22 20:18:51 2014
######################################################################

TEMPLATE = lib
CONFIG += dll
QT += qml quick widgets

TARGET = vsttest
INCLUDEPATH += .
VERSION = 1.0.0

SOURCES += vsttest.cpp
SOURCES += Ticker.cpp
HEADERS += aeffectx.h
HEADERS += Ticker.h
