name: ci
on: [push, pull_request]
jobs:
  ubuntu-22_04:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: sudo apt-get install -qy clang libsamplerate0-dev portaudio19-dev libvorbis-dev
      - uses: jurplel/install-qt-action@v3
        with:
          version: 6.4.3
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          meson-version: 1.0.1
        env:
          CXX: clang++
          PATH: /home/runner/work/wahjam2/Qt/6.4.3/gcc_64/libexec:/usr/bin:/bin
      - uses: actions/upload-artifact@v3
        with:
          name: testlog-ubuntu.txt
          path: build/meson-logs/testlog.txt
        if: ${{ always() }}

  windows-cross-compile:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/wahjam/wahjam2-windows-build:latest
      options: --user root # so actions work
    steps:
      - uses: actions/checkout@v3
      - run: export MESON=x86_64-w64-mingw32.shared-meson QMAKE=/mxe/usr/x86_64-w64-mingw32.shared/qt6/bin/qmake NINJA=/mxe/usr/x86_64-pc-linux-gnu/bin/ninja PATH=/mxe/usr/bin:/mxe/usr/x86_64-pc-linux-gnu/qt6/libexec:$PATH && $MESON -Dbuildtype=release build && cd build && $NINJA test
      - uses: actions/upload-artifact@v3
        with:
          name: testlog-windows-cross-compile.txt
          path: build/meson-logs/testlog.txt
        if: ${{ always() }}

  macos-12:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.2'
      - run: brew install libsamplerate qt6 qtkeychain portaudio libvorbis
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          meson-version: 1.0.1
        env:
          PKG_CONFIG_PATH: /usr/local/opt/qt@6/lib/pkgconfig
          PATH: /usr/local/opt/pipx_bin:/Users/runner/.cargo/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/usr/bin:/bin:/usr/sbin:/sbin
      - uses: actions/upload-artifact@v3
        with:
          name: testlog-macos.txt
          path: build/meson-logs/testlog.txt
        if: ${{ always() }}
